spring:
  application:
    name: supermarket

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: denis

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
